version: 0.2

phases:
  install:
    commands:
      - echo "Installing Corretto 8..."
  
  pre_build:
    commands:
      - echo "Fetching CodeArtifact token..."
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain nextwork --domain-owner 123456789012 --query authorizationToken --output text)
      - sed -i "s|CODEARTIFACT_TOKEN_PLACEHOLDER|$CODEARTIFACT_AUTH_TOKEN|g" settings.xml

  build:
    commands:
      - echo "Building with Maven..."
      - mvn -s settings.xml compile
      - mvn -s settings.xml package

artifacts:
  files:
    - target/nextwork-web-project.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no